align_method: auto
align_orientation_prior: vertical
bundle_outlier_filtering_type: AUTO
bundle_use_gcp: true
bundle_use_gps: false
feature_min_frames: 10000
feature_process_size: 2432
feature_type: SIFT
flann_algorithm: KDTREE
local_bundle_radius: 0
matcher_type: FLANN
matching_gps_distance: 0
matching_gps_neighbors: 0
matching_graph_rounds: 50
optimize_camera_parameters: true
processes: 64
reconstruction_algorithm: incremental
retriangulation_ratio: 2
sift_peak_threshold: 0.066
triangulation_type: ROBUST
undistorted_image_format: tif
undistorted_image_max_size: 3727
use_altitude_tag: true
use_exif_size: false
